// app/layout.tsx
import "./globals.css";
import { DM_Sans } from "next/font/google";
import Provider from "@/layout/Provider";
import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";

// ✅ Import DM Sans with variable
const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-dm-sans", // Will be used in CSS
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={dmSans.variable}>
      <body>
        <Provider>
          <Header />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
